#!/usr/bin/bash
# Install Fabric for Python 3 - version 1.14.post1

pip3 uninstall -y Fabric Fabric3 fabric
sudo apt-get update
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev
sudo apt-get install build-essential
sudo apt-get install python3-dev
sudo apt-get install libpython3-dev
pip3 install pyparsing
pip3 install appdirs
pip3 install setuptools
pip3 install cryptography
pip3 install bcrypt
pip3 install PyNaCl
pip3 install Fabric3
